# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3efed8304f048a139c40a8729a8bafa70d4c778224ab71231398d3d27ffd78dc630a42350a32ab1c2c6ff07c3ed9c197fe33580359fbcc9b925f9932b4f0c9bb

test:
  secret_key_base: 80dfe8ae60b503bd43c74db924b8ca3e4faa0c35db6aadcc345a25cc35de30d6d49b4d9c6a909bdecfae4f1e4279959031ea6894a34f7a4e0bd1b7c5c3e16d31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
